app/components/creators/shared/Collaborators/index.js, app/components/creators/shared/Collaborators/tests/index.test.js, app/components/creators/shared/Project/index.js, app/components/creators/shared/buttons/MediumButton.js, app/components/creators/shared/buttons/index.js, app/components/creators/shared/modals/Join/index.js, app/components/creators/shared/modals/TouchProject/index.js, app/components/creators/shared/modals/TouchProject/tests/index.test.js, app/components/creators/shared/modals/index.js, app/theme/creators.js
=> feat: build touch overlay

app/components/creators/shared/Collaborators/index.js, app/components/creators/shared/CreatorsDesktopHeader/index.js, app/components/creators/shared/Project/index.js, app/components/creators/shared/ProjectsSection/index.js, app/components/creators/shared/UniteSection/index.js, app/components/creators/shared/buttons/JoinNowButton.js, app/components/creators/shared/buttons/MediumButton.js, app/components/creators/shared/buttons/ProjectButton.js, app/components/creators/shared/modals/shared/ProjectFormHelperText.js, app/components/creators/shared/typography/Body.js, app/components/creators/shared/typography/Body13.js, app/components/creators/shared/typography/Body15.js, app/components/creators/shared/typography/Body18.js
=> fix: add font-family:unset

app/components/creators/CreatorsWrapper/index.js, app/components/creators/shared/CreatorsDesktopHeader/index.js, app/components/creators/shared/ProjectsSection/index.js, app/components/creators/shared/Wrapper.js, app/components/shared/Footer/index.js, app/theme/colors.js, app/theme/creators.js
=> fix: minor design update

app/components/creators/CreatorsWrapper/index.js, app/components/creators/shared/Collaborators/index.js, app/components/creators/shared/CreatorsDesktopHeader/index.js, app/components/creators/shared/CreatorsHeaderWrapper/index.js, app/components/creators/shared/Project/index.js, app/components/creators/shared/ProjectsSection/index.js, app/components/creators/shared/UniteSection/index.js, app/components/creators/shared/buttons/JoinNowButton.js, app/components/creators/shared/modals/Join/index.js, app/components/creators/shared/modals/ProjectProposal/index.js, app/components/creators/shared/typography/Body11.js, app/components/creators/shared/typography/index.js, app/theme/creators.js
=> fix: design update

app/api/tgpApi.js, app/components/creators/shared/Project/index.js, app/components/creators/shared/UniteSection/index.js, app/components/creators/shared/buttons/JoinNowButton.js, app/components/creators/shared/modals/shared/BodyWrapper.js
=> feat: design fix

app/api/tgpApi.js, app/components/creators/shared/Project/index.js
=> feat: update ICH logic

app/components/creators/shared/Project/index.js, app/components/creators/shared/ProjectsSection/index.js
=> feat: add ICH form link

app/api/tgpApi.js, app/components/creators/shared/Project/index.js, app/components/creators/shared/UniteSection/index.js, app/components/creators/shared/buttons/ViewProjectsButton.js, app/components/creators/shared/buttons/index.js
=> feat: add custom link to ich

app/components/creators/shared/Heads/index.js, app/components/creators/shared/UniteSection/index.js, app/components/creators/shared/buttons/ViewProjectsButton.js
=> feat: add global ich button

app/api/tgpApi.js, app/components/intro/ZipFinderWrapper/index.js, app/components/shared/SnackbarWrapper/index.js, cypress/integration/intro/zipFinder.spec.js
=> feat: add cypress test to intro/zip-finder

app/components/shared/navigation/DesktopHeader.js, app/components/shared/navigation/NavWrapper.js, cypress/integration/shared/guestHeader.spec.js
=> feat: add cypress test to guest header

app/components/elections/DistrictWrapper/index.js, cypress/integration/district/district.spec.js
=> feat: add election link test to district page

app/components/elections/DistrictWrapper/index.js, app/components/elections/ElectionWrapper/FiltersPopup.js, app/components/elections/ElectionWrapper/index.js, app/components/elections/VsList.js, app/components/shared/BottomPopup.js, app/containers/elections/ElectionPage/index.js, cypress/fixtures/content.json, cypress/integration/district/district.spec.js, cypress/integration/election/election.spec.js, cypress/integration/party/events.spec.js, cypress/integration/party/party.spec.js, cypress/support/commands/base.js, cypress/support/commands/district.js, cypress/support/commands/election.js, cypress/support/commands/index.js, cypress/support/commands/party.js, cypress/support/commands/request.js
=> feat: build automation tests for election page

app/api/tgpApi.js, app/components/elections/CandidateWrapper/index.js, app/containers/elections/CandidatePage/index.js, app/helpers/candidatesHelper.js, cypress/constants.js, cypress/fixtures/content.json, cypress/integration/candidate/candidate.spec.js, cypress/support/commands/candidate.js, cypress/support/commands/district.js, cypress/support/commands/election.js, cypress/support/commands/index.js, cypress/support/commands/request.js, cypress/support/utils.js
=> feat:build the automation tests for candidate page

cypress/fixtures/content.json, cypress/integration/candidate/candidate.spec.js, cypress/integration/district/district.spec.js, cypress/integration/election/election.spec.js, cypress/integration/you/you.spec.js, cypress/support/commands/request.js, package-lock.json, package.json
=> fix: add cypress-promise

app/components/elections/DistrictWrapper/index.js, app/components/elections/SupportersProgressBar.js, cypress/integration/district/district.spec.js
=> fix: text bugs

app/components/elections/CandidateWrapper/FincanicalText.js, app/components/elections/CandidateWrapper/FollowTheMoney.js
=> fix: format number in candidate page

app/components/you/CrewMember/index.js, app/components/you/CrewWrapper/index.js, app/components/you/ProfileWrapper/index.js, app/containers/you/CrewPage/index.js, cypress/constants.js, cypress/fixtures/content.json, cypress/integration/you/leaderboard.spec.js, cypress/integration/you/you.spec.js, cypress/support/commands/party.js, cypress/support/commands/request.js, cypress/support/commands/you.js
=>  fix: update specs /  feat: add qa test for leaderboard

app/components/shared/Ama.js, app/containers/shared/AmaContainer/actions.js, app/containers/shared/AmaContainer/index.js, app/containers/shared/AmaContainer/saga.js, app/helpers/emailHelper.js
=> feat: upgrade ama container

cypress/fixtures/content.json, cypress/support/commands/base.js
=> fix: update specs for ama container

app/components/shared/Ama.js, cypress/fixtures/content.json, cypress/support/commands/base.js
=> fix: update ama container

app/components/shared/Ama.js
=> fix: close modal after submit

app/components/elections/CandidateWrapper/TopRow.js, app/components/elections/ElectionWrapper/ShareModal.js, app/components/you/ProfileWrapper/ShareModal.js, app/components/you/ProfileWrapper/index.js
=> fix: fix share links

app/components/you/CrewWrapper/index.js, cypress/fixtures/content.json, cypress/integration/you/leaderboard.spec.js, cypress/support/commands/base.js, cypress/support/commands/you.js
=> fix: update failed specs except login/register

app/components/you/LoginWrapper/index.js, cypress.json, cypress/integration/auth/login.spec.js, cypress/support/commands/auth.js
=> feat: add specs for email/pwd login

app/components/you/ProfileWrapper/ChangePasswordModal.js, cypress/integration/auth/login.spec.js, cypress/integration/auth/password.spec.js, cypress/support/commands/auth.js
=> feat: add specs for password change

app/components/you/EmailRegisterWrapper/index.js, app/components/you/LoginWrapper/index.js, app/components/you/ProfileWrapper/ChangePasswordModal.js, cypress.json, cypress/integration/auth/login.spec.js, cypress/integration/auth/password.spec.js, cypress/integration/auth/register.spec.js, cypress/support/commands/auth.js
=> fix: update specs for register

app/components/you/CrewWrapper/index.js
=> feat: add share section to leaderboard

app/components/creators/CreatorsWrapper/index.js, app/components/creators/shared/modals/Join/index.js, app/components/shared/buttons/OutlinedButton.js, app/containers/creators/CreatorsPage/index.js
=> feat: add twitter social login to creators

server/index.js, server/sitemap.js
=> fix: sitemap bug

server/sitemap.js
=> candidateRoute import issue

app/api/tgpApi.js, server/sitemap.js
=> feat: add faqs to sitemap

app/components/you/SocialRegisterWrapper/TwitterButton.js, cypress/integration/auth/login.spec.js, cypress/support/commands/auth.js
=> fix: update specs

app/components/shared/UserAvatar.js
=> fix: avatar squash issue

app/containers/elections/CandidatePage/index.js, app/containers/elections/CandidatePage/saga.js
=> fix: redirect candidate page for hidden candidates to 404

Jenkinsfile
=> fix: update jenkinsfile

Jenkinsfile
Reverts thegoodparty/tgp-webapp#76
=> Revert "fix: update jenkinsfile"

app/components/shared/EventSnippet.js
=> feat: add video to crowcast event snippent

app/components/elections/ElectionWrapper/ShareModal.js, app/helpers/candidatesHelper.js
=> fix: language for share modal

app/components/shared/typogrophy/Quote.js, app/containers/HomePage/saga.js
fix: remove doubled h1 tag on homepage
=> fix: validate email before subscribing

app/api/tgpApi.js, app/components/voterize/VerifyVoteWrapper/index.js, app/containers/voterize/VerifyVotePage/actions.js, app/containers/voterize/VerifyVotePage/constants.js, app/containers/voterize/VerifyVotePage/index.js, app/containers/voterize/VerifyVotePage/saga.js, app/containers/you/YouPage/index.js, app/helpers/dateHelper.js, app/helpers/phoneHelper.js
=> update voter registration

app/components/voterize/VerifyVoteWrapper/index.js
=> set email as required

app/components/elections/ElectionWrapper/index.js, app/components/voterize/VerifyVoteWrapper/index.js, app/containers/elections/ElectionPage/index.js, app/containers/voterize/VerifyVotePage/actions.js, app/containers/voterize/VerifyVotePage/constants.js, app/containers/voterize/VerifyVotePage/index.js, app/containers/voterize/VerifyVotePage/reducer.js, app/containers/voterize/VerifyVotePage/saga.js
=> add verify voter between join a bloc and share

app/components/elections/ElectionWrapper/index.js, app/components/shared/Stepper.js, app/components/voterize/VerifyVoteWrapper/index.js, app/components/you/SocialRegisterWrapper/index.js, app/containers/you/SocialRegisterPage/index.js, app/containers/you/YouPage/index.js
=> redirect to voter verify form just after register on election page

app/components/voterize/VerifyVoteWrapper/index.js, package-lock.json
=> update design for verify respose

app/components/you/SocialRegisterWrapper/index.js
=> fix: update join tgp modal text

app/components/shared/customInputFormat/DobFormat.js, app/components/shared/customInputFormat/PhoneNumberFormat.js
=> add PropTypes

app/components/elections/ElectionWrapper/ChoiceModal.js
=> remove stepper for external link

app/components/elections/DistrictWrapper/index.js, app/components/elections/ElectionWrapper/index.js
=> update text on candidate page

app/containers/App/Routes.js, app/containers/admin/AdminEditCandidatePage/index.js, app/containers/elections/CandidatePage/index.js
=> not redirect to 404

app/components/elections/CandidateWrapper/ShareModal.js
=> fix aspect ratio for share buttons

app/components/shared/Footer/index.js
=> fix: remove disclaimer bg for creators

app/api/tgpApi.js, app/components/admin/AdminEditCandidate/JoditEditor.js
=> add upload to jodit editor

pages/elections/incumbents.js
=> uncomment incumbents render

components/shared/UserAvatar.js, components/shared/navigation/DesktopHeader.js, components/shared/navigation/MobileHeader.js
=> fix nav issues

components/shared/navigation/MobileHeader.js
=> change drawer direction

components/shared/navigation/DesktopHeader.js, components/shared/navigation/MobileHeader.js
=> fix: UX issues on new nav

components/elections/CandidateNewWrapper/CompareCandidate.js, components/elections/CandidateNewWrapper/Main.js, components/elections/CandidateNewWrapper/ProfileInfo.js, components/elections/CandidateNewWrapper/RecentlyJoined.js, components/elections/CandidateNewWrapper/index.js, components/elections/SupportersProgressBar.js, components/home/ChallengersSection/ChallengerAvatar.js
=> feat: update candidate design

components/elections/CandidateNewWrapper/Main.js, components/elections/CandidateNewWrapper/ProfileInfo.js, components/elections/CandidateNewWrapper/index.js, components/home/ChallengersSection/ChallengerAvatar.js, components/shared/buttons/PurpleButton.js, components/shared/navigation/DesktopHeader.js, components/shared/navigation/MobileHeader.js
fix: update profile section on mobile
=> fix: update designs

components/home/HomePageWrapper/index.js
=> feat: hide challengers section

components/elections/ShareImageWrapper/index.js
=> update share image style

components/elections/ShareImageWrapper/index.js
=> fix share image style

components/elections/ShareImageWrapper/index.js, components/party/FaqArticleWrapper/index.js
=> fix distorted avatar on previewing an endorsement

components/party/FaqArticleWrapper/index.js
=> update button on article

components/party/FaqArticleWrapper/index.js, containers/you/EmailConfirmationPage/index.js, helpers/queryHelper.js
=> verify email error

components/elections/CandidateNewWrapper/ProfileInfo.js
=> candidate detail page right margin cut

components/elections/CandidateNewWrapper/EndorsementPreviewModal.js, components/elections/CandidateNewWrapper/RecentlyJoined.js, components/elections/CandidateNewWrapper/index.js, components/elections/ShareImageWrapper/index.js
=> endorse count is missing on preview modal

components/CandidatesWrapper/index.js
=> fix scroll issue on candidate page

containers/App/content.js, pages/about.js, pages/admin/add-candidate/[id].js, pages/admin/stage-settings/[id].js, pages/candidate/[...NameIdTab].js, pages/candidates.js, pages/embed/redirect/[id].js, pages/good-practices.js, pages/index.js, pages/lp/[slug].js, pages/share-image/[id].js
=> add try catch

containers/admin/AdminAddCandidatePage/saga.js
=> trailing issue

components/shared/UserAvatar.js
=> fix leaderboard avatar issue

api/tgpApi.js, components/admin/AdminTopIssueRequestsWrapper/RequestTopTab.js, components/admin/AdminTopIssueRequestsWrapper/index.js, components/admin/AdminTopIssueRequestsWrapper/tests/index.test.js, components/admin/AdminUpdateRequestsWrapper/index.js, containers/admin/AdminTopIssueRequestsPage/actions.js, containers/admin/AdminTopIssueRequestsPage/constants.js, containers/admin/AdminTopIssueRequestsPage/index.js, containers/admin/AdminTopIssueRequestsPage/reducer.js, containers/admin/AdminTopIssueRequestsPage/saga.js, containers/admin/AdminTopIssueRequestsPage/selectors.js, containers/admin/AdminTopIssueRequestsPage/tests/actions.test.js, containers/admin/AdminTopIssueRequestsPage/tests/index.test.js, containers/admin/AdminTopIssueRequestsPage/tests/reducer.test.js, containers/admin/AdminTopIssueRequestsPage/tests/saga.test.js, containers/admin/AdminTopIssueRequestsPage/tests/selectors.test.js, containers/admin/AdminUpdateRequestsPage/actions.js, containers/admin/AdminUpdateRequestsPage/constants.js, containers/admin/AdminUpdateRequestsPage/index.js, containers/admin/AdminUpdateRequestsPage/reducer.js, containers/admin/AdminUpdateRequestsPage/saga.js, pages/admin/top-issue-requests.js
=> add accept/reject section for top issues

api/tgpApi.js, components/admin/AdminLeftMenu/index.js, components/admin/AdminReleasesWrapper/index.js, components/admin/AdminReleasesWrapper/tests/index.test.js, containers/admin/AdminReleasesPage/Loadable.js, containers/admin/AdminReleasesPage/actions.js, containers/admin/AdminReleasesPage/constants.js, containers/admin/AdminReleasesPage/index.js, containers/admin/AdminReleasesPage/reducer.js, containers/admin/AdminReleasesPage/saga.js, containers/admin/AdminReleasesPage/selectors.js, containers/admin/AdminReleasesPage/tests/actions.test.js, containers/admin/AdminReleasesPage/tests/index.test.js, containers/admin/AdminReleasesPage/tests/reducer.test.js, containers/admin/AdminReleasesPage/tests/saga.test.js, containers/admin/AdminReleasesPage/tests/selectors.test.js, pages/admin/releases.js
=> add new release page for admin

api/tgpApi.js, components/candidate-portal/CampaignNotificationWrapper/index.js, components/candidate-portal/CampaignNotificationWrapper/tests/index.test.js, components/candidate-portal/PortalLeftMenu/index.js, containers/candidate-portal/CampaignNotificationPage/actions.js, containers/candidate-portal/CampaignNotificationPage/constants.js, containers/candidate-portal/CampaignNotificationPage/index.js, containers/candidate-portal/CampaignNotificationPage/reducer.js, containers/candidate-portal/CampaignNotificationPage/saga.js, containers/candidate-portal/CampaignNotificationPage/selectors.js, containers/candidate-portal/CampaignNotificationPage/tests/actions.test.js, containers/candidate-portal/CampaignNotificationPage/tests/index.test.js, containers/candidate-portal/CampaignNotificationPage/tests/reducer.test.js, containers/candidate-portal/CampaignNotificationPage/tests/saga.test.js, containers/candidate-portal/CampaignNotificationPage/tests/selectors.test.js, pages/candidate-portal/campaign-notification.js
=> email notification setting

components/ChangeLogWrapper/index.js, components/ChangeLogWrapper/tests/index.test.js, components/admin/AdminReleasesWrapper/index.js, containers/ChangeLogPage/Loadable.js, containers/ChangeLogPage/actions.js, containers/ChangeLogPage/constants.js, containers/ChangeLogPage/index.js, containers/ChangeLogPage/reducer.js, containers/ChangeLogPage/saga.js, containers/ChangeLogPage/selectors.js, containers/ChangeLogPage/tests/actions.test.js, containers/ChangeLogPage/tests/index.test.js, containers/ChangeLogPage/tests/reducer.test.js, containers/ChangeLogPage/tests/saga.test.js, containers/ChangeLogPage/tests/selectors.test.js, pages/changelog.js
=> update admin release/build changelog

components/elections/CandidateNewWrapper/RecentlyJoined.js
=> 6799 - fix issue for long endorse name

components/entrance/PasswordCreationWrapper/index.js
=> 6816 - add strong validation for password

containers/entrance/RegisterPage/saga.js
=> 6802 - show correct error text

components/profile/ProfileSettingsWrapper/PersonalSection.js, components/profile/ProfileSettingsWrapper/index.js, containers/profile/ProfileSettingsPage/index.js
=> 7243: profile name update propagate issue

components/entrance/LoginPasswordWrapper/index.js
=> 6810- fix recovery link sent message

components/profile/ProfileSettingsWrapper/PersonalSection.js
=> Fix profile page issue

components/admin/AdminReleasesWrapper/index.js
=> 5736 - update label for audience

components/entrance/RegisterWrapper/index.js
=> 6802 - add helpertext to let user know about the maximum char limit

components/admin/AdminCandidateUpdatesWrapper/index.js, components/candidate-portal/CandidatePortalHomeWrapper/CampaignStats.js
=> 8433- fix issues on candidate portal

components/profile/ProfileSettingsWrapper/PersonalSection.js
=> fix issue for update email

components/entrance/PasswordCreationWrapper/index.js, components/entrance/ResetPasswordWrapper/index.js, components/profile/ProfileSettingsWrapper/PersonalSection.js, containers/entrance/ResetPasswordPage/saga.js, helpers/userHelper.js
=> 6810- change password rule for all places

components/elections/CandidateNewWrapper/RecentlyJoined.js, components/profile/LeaderboardWrapper/LeaderboardPerson.js, components/profile/ProfileSettingsWrapper/ImageSection.js, containers/profile/ProfilePage/index.js, helpers/userHelper.js
=> 7243 - fix display name update issue/avatar issue

components/ChangeLogWrapper/index.js, components/admin/AdminReleasesWrapper/index.js
=> 5736: fix issue on change log
